FROM zenoss/%FROM_IMAGE%

ENV ZENHOME=/opt/zenoss

COPY %SHORT_VERSION%.x /root/%SHORT_VERSION%.x

# TODO: fix this. The hubpasswd file should be in the service definition
COPY hubpasswd /opt/zenoss/etc/

COPY install_scripts component_info /opt/zenoss/install_scripts/

RUN /opt/zenoss/install_scripts/zenoss_component_install.sh %INSTALL_OPTIONS%
